### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by 0xadada**

### CODE REVIEW

**Review by sdhull — APPROVED** [review]

**Comment by sdhull** [comment]
I approve, even though my approval is meaningless 😂

**Comment by kellyselden** [comment]
The deployment keys on Travis are out of date, so even if I merge this, it won't take affect. I'm not sure who has access.

**Comment by kratiahuja** [comment]
@rwjblue do you have access to the deployment keys on travis?

**Comment by rwjblue** [comment]
@kratiahuja I think the encrypted variable for heroku deployment in the `.travis.yml` [here](https://github.com/ember-fastboot/fastboot-website/blob/124cf6fcffb0e96ed60b5b259f1719e71bbca1c6/.travis.yml#L34) is what @kellyselden was meaning. I don't know that I have access to this app in the heroku dashboard, we should see if @tomdale can add us both...

**Comment by locks** [comment]
@0xadada thanks! sorry for the derpiness with the branch.

**Pull request closed without merging**
